name: iOS App Release Build

on:
  push:
    branches: [ios]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Node 
        uses: actions/setup-node@v4
        with:
            node-version: 20

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Build iOS app
        run: eas build --platform ios --local --non-interactive --output ${{ github.workspace }}/app-release.ipa

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: expo-bare-ios
          path: ${{ github.workspace }}/app-release.ipa
